- hosts: direct
  become: True
  become_method: sudo
  gather_facts: yes
  roles:
  - name: devpackages
    tags: devpackages
  - name: iproute2
    tags: iproute2
  - name: frrouting
    tags: frrouting
  - name: fdk
    tags: fdk
